Missing dependency for inference_client.py
Added a missing dependency required by the inference_client.py to the install line. Error on my environment was:

 File "inference_client.py", line 13, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'