Added two additional Helm parameters
If you do not add these two parameters the Grafana installation fails with the following message since because it identifies a mismatch with PodSecurityPolicy API version. 

TeamRole:~/environment $ helm install grafana grafana/grafana \
>     --namespace grafana \
>     --set persistence.storageClassName="gp2" \
>     --set persistence.enabled=true \
>     --set adminPassword='EKS!sAWSome' \
>     --values ${HOME}/environment/grafana/grafana.yaml \
>     --set service.type=LoadBalancer
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: resource mapping not found for name: "grafana" namespace: "" from "": no matches for kind "PodSecurityPolicy" in version "extensions/v1beta1"
ensure CRDs are installed first