Correct command to upgrade / install the handler
Original command fails: 

````
helm install aws-node-termination-handler eks/aws-node-termination-handler \
>              --namespace kube-system \
>              --set nodeSelector.lifecycle=Ec2Spot
Error: This command needs 1 argument: chart name

````
Updated to "upgrade --install" -- as per  https://github.com/aws/aws-node-termination-handler -- and correct command format