Update test_hpa.md
--generator flag has been deprecated.

```
~/Workspace/Experiments/eksworkshop ❯ kubectl --generator=run-pod/v1 run -i --tty load-generator --image=busybox /bin/sh                 
                                                                                                                                         
error: unknown flag: --generator
See 'kubectl run --help' for usage.
```