Add mandatory flag --cluster for eksctl >= 0.80.0
Starting from eksctl 0.80.0 requires --cluster flag. 

eksctl 0.80.0
Failure: 
eksctl utils write-kubeconfig eksworkshop-eksctl          
Error: --cluster=eksworkshop-eksctl and argument eksworkshop-eksctl cannot be used at the same time

Success: 
eksctl utils write-kubeconfig --cluster=eksworkshop-eksctl                                                                                              
2022-01-24 16:51:16 [i]  eksctl version 0.80.0
2022-01-24 16:51:16 [i]  using region eu-west-1
2022-01-24 16:51:16 [✔]  saved kubeconfig as "/tmp/kubeconfig-dev"